### ISSUE TITLE
Backup error

### ISSUE THREAD

**Issue by scarecr0w12** [jkroepke/2Moons#260] opened 2016-08-25 17:59 UTC
> USER ERROR
> Message: Error after executing SHOW CREATE TABLE uni2_aks! Can't find key 'Create Table' in the results. Available data: Array ( [0] => Array ( [Table] => uni2_aks [Create Table] => CREATE TABLE `uni2_aks` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `name` varchar(50) DEFAULT NULL, `target` int(11) unsigned NOT NULL, `ankunft` int(11) DEFAULT NULL, PRIMARY KEY (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 ) ) 
> File: /includes/classes/SQLDumper.class.php
> Line: 103
> URL: http://********/admin.php?page=dump
> PHP-Version: 5.6.21
> PHP-API: apache2handler
> MySQL-Client-Version: mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $
> 2Moons Version: 1.8.git
> Debug Backtrace:
> #0 /includes/classes/SQLDumper.class.php(28): SQLDumper->softwareDumpToFile(Array, 'includes/backup...')
> #1 /includes/pages/adm/ShowDumpPage.php(42): SQLDumper->dumpTablesToFile(Array, 'includes/backup...')
> #2 /admin.php(199): ShowDumpPage()
> #3 {main}

Just did a fresh install, and attempted a backup of the entire DB, this is the error i get. Also was unable to Upgrade from previous due to this error (Hence why i fresh installed)

The server is running under windows XAMPP. Any idea what the issue is?

**Comment by jkroepke** [comment] 2016-08-26 07:45
Yes. Duplicate of #250

**Closed by jkroepke** 2016-08-26 07:45 UTC
