### ISSUE TITLE
Notes template

### ISSUE THREAD

**Issue by terassiel** [jkroepke/2Moons#94] opened 2015-11-11 23:32 UTC
I got an error in the notes page :
Message: Undefined variable: _tmp2
File: /cache/templates/de^660de8461ba3db527d260806cc37d9204f819346.page.notes.default.tpl.php
Line: 224

I fixed it by changing line 224 from:
} elseif ($_tmp2 == 2) {?>
to:
} elseif ($_tmp1 == 1) {?>
and the error went away, but I am wondering where it came from in the first place, eg where is that cache file created?

**Comment by Hilarious001** [comment] 2015-11-13 01:58
where did u find the tmp2 code ?

**Comment by wumix** [comment] 2015-11-13 07:25
What do you mean my friend?
Am 13.11.2015 02:58 schrieb "Hilarious001" <notifications@github.com>:

**Comment by terassiel** [comment] 2015-11-13 09:36
When I opened the "notes" page the error I posted came.
The error was in a cache file in the directory /cache/templates/de^(and en^)(digit combination).pages.notes.default.tpl.php
I am using the latest version with all the new changes and I´m looking for the file that creates these cache files to fix it permanently.

**Comment by wumix** [comment] 2015-11-13 10:13
Only 2 temp folders is for 2Moons.
One in cache and one in cache/templates you know what I mean?
Am 13.11.2015 02:58 schrieb "Hilarious001" <notifications@github.com>:

**Comment by terassiel** [comment] 2015-11-13 10:16
Yes and the corrupt file was in cache/templates.
My question is how it gets created. I dont want to fix the error everytime the temp folder get renewed....

**Comment by OzanKurt** [comment] 2015-11-13 10:18
Change smarty settings, this will help fix that error but will make your app lose performance.

Ozan Kurt

**Comment by terassiel** [comment] 2015-11-13 10:27
and what should I change there? My guess is you mean /includes/libs/Smarty/smarty.class.php ?

**Comment by OzanKurt** [comment] 2015-11-13 10:32
class .Template.php

cache settings

Ozan Kurt

**Comment by Hilarious001** [comment] 2015-11-13 13:17
there must be another way to fix this then your app losing performance

**Comment by Hilarious001** [comment] 2015-12-11 19:35
Fixed in the default notes templates you are using {$notesRow.priority} twice time

remove the {} from that and it will work again

Dont listen to ozan response

**Comment by OzanKurt** [comment] 2015-12-11 19:43
-.-

**Comment by Hilarious001** [comment] 2015-12-14 15:34
For sure you are working on this pack and you are saying sh*t, this is not possible, even don't know how jan taked you as contrib.
---->
Change smarty settings, this will help fix that error but will make your app lose performance. Ozan Kurt
<----

**Comment by OzanKurt** [comment] 2015-12-15 02:50
Why are you even so offensive?

**Comment by Hilarious001** [comment] 2015-12-15 20:51
You are working on something and you give answers to people without even checking what the problem is,

That are reasons, why people don't use 2moons anymore. the support is to crappy and when there is support, it are usualy false answers that give other users a bad experience and make them stop using it.

As contrib. you should be able to give correct answers for the people using it, atleast, my though on this.

**Comment by terassiel** [comment] 2015-12-20 13:48
Hi Hilarious001, the fix you provided solved the imminet Problem but the notes now can not be deleted.

Best regards,
Terassiel

**Comment by Hilarious001** [comment] 2015-12-24 23:41
you right terassiel, il keep you updated once fixed in my version, didnt noticed it, but what you said above is another problem then the first one, it answer have no effect on that issue

Will post a pull request when fixed

**Comment by terassiel** [comment] 2015-12-28 17:28
works like a charm ;) Thank you verry much

**Closed** 2015-12-28 17:28 UTC
