### ISSUE TITLE
MissionCase 4 Duplication Bug

### ISSUE THREAD

**Issue by OzanKurt** [jkroepke/2Moons#196] opened 2016-05-27 18:00 UTC
Can we please check the code? I am trying to find an issue.

**Comment by Hilarious001** [comment] 2016-05-29 22:42
can you add a screen i didnt unerstand the problem

**Comment by OzanKurt** [comment] 2016-05-29 22:51
A bug occurs when you send the fleets with `%10` speed to `MissionCaseStay` mission `(id = 4)` and it duplicates the resources you sent with your fleet.

**Comment by Hilarious001** [comment] 2016-05-30 01:55
tested, i dont have it

Regards

**Comment by lilmnm-kamikaze-** [comment] 2016-05-30 08:24
For the code I have XG-Project. we had an issue where the fleet would duplicate (ships and any res with the ships.) It would happen if the target destination owner and the fleet owner
s account was offline for the fleet to land at the destination and when it returned  to the origin then one of them would log in or a planet update would occur (by a spy for example) the fleet would return but would double. The cause was the table lock query wasn't working properly so each account would run the fleet return script twice making the fleet doubled. 

Sorry for writing that if it doesn't seem to be the case here but we spent a few weeks narrowing down the cause and just trying to save you guys some time.

**Comment by OzanKurt** [comment] 2016-05-30 08:32
Wow, this might me the thing.

My script is probably old then, should I just replace the 1.7.3 version of FleetStepPages and Mission cases to fix?

**Comment by lilmnm-kamikaze-** [comment] 2016-05-30 08:51
XGP and 2moons mission control code is different and i don't see a lock table query in the fleetRestore() or fleetKill() functions. You should test this with two accounts and have one attack the other. The way we tested it was sent 10 waves of 100 small cargos to an offline or inactive player then sign out our selves and wait until all the fleets returned Then we waited a few extras minutes then we looked to the small cargo amount. Also double battle reports or transport reports with the same timestamp also occurred when a duplication happened.

**Comment by OzanKurt** [comment] 2016-05-30 11:05
I will have a look asap.

**Comment by jkroepke** [comment] 2016-05-31 19:55
It is 100% reproducible 
* on your system?
* on the lastest 2moons version?

**Comment by jkroepke** [comment] 2016-05-31 20:04
@lilmnm-kamikaze- I see the LOCK TABLE implementations https://github.com/XGProyect/XG-Proyect-v3.x.x/blob/master/src/xgp3.0.0/upload/application/libraries/MissionControlLib.php#L43. I remove it for performance reasons. Instead LOCK TABLE, i'm using a own locking method. (https://github.com/jkroepke/2Moons/blob/master/includes/FleetHandler.php#L21). 

i'm interested, if it happens on the latest version.

**Comment by OzanKurt** [comment] 2016-06-01 09:36
I am using 1.7.3 of 2moons.

**Comment by OzanKurt** [comment] 2016-06-01 09:36
A guy is using this bug, I couldn't manage to do so yet.

**Comment by jkroepke** [comment] 2016-06-01 09:53
2moons logging all fleet actions, maybe you can see something different...

**Comment by Hilarious001** [comment] 2016-06-01 09:57
At least PDO version i dont have any bug of duplicates

Regards

**Comment by OzanKurt** [comment] 2016-06-01 10:11
It's not about the 1.8 anyways.

**Comment by Hilarious001** [comment] 2016-06-01 10:14
I know but jan asked :) so he now hes new version is correct

**Comment by lilmnm-kamikaze-** [comment] 2016-06-01 11:35
@jkroepke Ahh there it is. sorry I didnt look at the top in the page construction. Had a brain fart. I don't plan to have more then 300 players active at one time so I am fine with a little performance hit. 

But for the version i have (not 2moons but XGP) it would happen 90% of the time when both players were offline at the time the fleet landed at the target and when the fleet returned home.

**Comment by jkroepke** [comment] 2016-06-01 15:25
Okay, never hear this behavior in the last years here

**Comment by lilmnm-kamikaze-** [comment] 2016-06-01 15:29
Most people would try to keep it a secret to grow quickly but we caught it during testing. Then we had an alliance statistics bug that halted the server. But was unrelated.

**Comment by jkroepke** [comment] 2016-06-01 15:37
@ozankurt: To help you, we need your game Files. FleetHandler, related mission functions, e.g.

**Comment by OzanKurt** [comment] 2016-06-01 19:13
I will upload the files asap.

**Comment by jkroepke** [comment] 2016-06-06 14:56
If you find the time, I will reopen it. You can still write here.

**Closed** 2016-06-18 09:18 UTC
Labels: waiting on feedback
